"""A synthetic walking session, cut to the same length as the real recording.

Pulsoid streams heart rate and nothing else. With one signal there is no
movement gate, so a rise and a rise-because-you-stood-up look identical. This
file supplies the missing half as an explicit, labelled counterexample rather
than as a guess about what the wearer was doing: a walking session of exactly
the same duration and grid, laid alongside the real one.

HR is not drawn by hand here. Cadence is, and HR follows it:

    demand(t) = HR_rest + GAIN * cadence(t) + stress(t)
    dHR/dt    = (demand - HR) / tau            tau_up < tau_down

which is the standard first-order approximation to the on-kinetics of heart
rate under a step change in workload. That matters for what this page is for:
the walking rises are *generated by cadence*, so when the detector stays quiet
through them it is the gate doing the work, not a lucky threshold.

Stress events are the same equation with cadence pinned at zero -- a demand
step with no mechanical cause. Those are what must fire. Their size is taken
from the real recording rather than picked: the clearest unexplained climb in
the Pulsoid file is +20 bpm at 19 bpm/min, so the synthetic ones are built to
land in that range instead of being tuned until the detector likes them.
"""
import pathlib
import numpy as np
import pandas as pd

SEED = 137
GRID_S = 10
DT_MIN = GRID_S / 60.0

HR_REST = 64.0
GAIN = 0.42           # bpm per step/min. 110 spm -> ~110 bpm steady state
TAU_UP = 42.0         # s. HR chases a rising demand quickly
TAU_DOWN = 105.0      # s. and gives it up slowly -- recovery lags, as it does
DRIFT = 0.055         # bpm/min of cardiac drift per minute of continuous walking
ONSET_SLOPE = 4.0     # bpm/min. below this the response has stopped rising

# (start_min, end_min, cadence_spm, stress_bpm, kind, label)
#   kind drives the ground-truth banding in the viewer and the scoring.
#   stress_bpm is a demand offset applied with NO cadence behind it.
SEGMENTS = [
    (  0.0,  12.0,   0,  0, "baseline",         "seated, settling"),
    ( 12.0,  15.5,   0, 24, "stress_onset",     "inbox opens"),
    ( 15.5,  22.0,   0,  0, "recovery",         "coming down"),
    ( 22.0,  48.0, 105,  0, "activity",         "walk, steady"),
    ( 48.0,  57.0,   0,  0, "recovery",         "sat down"),
    ( 57.0,  61.0,   0, 30, "stress_onset",     "phone call"),
    ( 61.0,  67.0,   0,  0, "recovery",         "coming down"),
    ( 67.0,  96.0, 118,  0, "activity",         "walk, brisk"),
    ( 96.0, 104.0,  26,  0, "negative_control", "standing, shifting"),
    (104.0, 112.0,   0,  0, "baseline",         "seated"),
    (112.0, 115.5,   0, 27, "stress_onset",     "deadline lands"),
    (115.5, 124.0,   0,  0, "recovery",         "coming down"),
    (124.0, 138.0,  98,  0, "activity",         "walk, flat"),
    (138.0, 146.0,  88, 14, "activity",         "walk, uphill"),
    (146.0, 152.0, 100,  0, "activity",         "walk, over the top"),
    (152.0, 162.0,   0,  0, "recovery",         "sat down"),
    (162.0, 165.0, 145,  0, "negative_control", "stairs"),
    (165.0, 174.0,   0,  0, "recovery",         "coming down"),
    (174.0, 188.0, 112,  0, "activity",         "walk, home"),
    (188.0, 196.0,   0,  0, "baseline",         "seated"),
    (196.0, 199.5,   0, 22, "stress_onset",     "one more email"),
    (199.5, 999.0,   0,  0, "recovery",         "coming down"),
]

# watch dropouts, (start_min, duration_min) -- the strap works loose on a walk
DROPOUTS = [(31.0, 1.5), (74.5, 2.0), (129.0, 0.7), (180.0, 1.2)]


def _ramp(n, width):
    """Cadence does not switch on as a step -- you take a few seconds to
    reach pace and a few to stop. Half-cosine both ends."""
    w = min(int(width), n // 2)
    if w < 1:
        return np.ones(n)
    e = 0.5 - 0.5 * np.cos(np.linspace(0, np.pi, w + 2)[1:-1])
    out = np.ones(n)
    out[:w] = e
    out[-w:] = e[::-1]
    return out


def build(n, rng):
    cad = np.zeros(n)
    stress = np.zeros(n)
    kind = np.array(["baseline"] * n, dtype=object)
    label = np.array([""] * n, dtype=object)

    for s, e, c, sb, k, lb in SEGMENTS:
        a, b = int(s / DT_MIN), min(int(e / DT_MIN), n)
        if b <= a:
            continue
        m = b - a
        cad[a:b] = c * _ramp(m, 6)
        # an acute surge: on within a few seconds, held while the thing is
        # happening, then bled off. an impulse would be filtered away by the
        # 42 s cardiac time constant before HR could respond to it at all.
        if sb:
            u = np.linspace(0, 1, m)
            stress[a:b] = sb * np.minimum(1.0, (1 - np.exp(-u / 0.05))) \
                             * np.exp(-np.clip(u - 0.55, 0, None) / 0.30)
        kind[a:b] = k
        label[a:b] = lb

    # step-to-step variability: cadence is regular, footfall counting is not
    cad = np.where(cad > 0, cad + rng.normal(0, 2.4, n), 0.0)
    cad = np.clip(cad, 0, None)

    # cardiac drift: the longer you have been walking, the higher HR sits for
    # the same cadence. accumulates while moving, bleeds off while still.
    drift = np.zeros(n)
    acc = 0.0
    for i in range(n):
        acc = acc + DRIFT * DT_MIN if cad[i] > 30 else max(0.0, acc - 2 * DRIFT * DT_MIN)
        drift[i] = acc

    demand = HR_REST + GAIN * cad + stress + drift

    hr = np.empty(n)
    hr[0] = HR_REST
    for i in range(1, n):
        tau = TAU_UP if demand[i] > hr[i - 1] else TAU_DOWN
        hr[i] = hr[i - 1] + (demand[i] - hr[i - 1]) * (1 - np.exp(-GRID_S / tau))
    clean = hr.copy()      # noiseless, for splitting the labels below

    # sensor noise: a slow wander plus per-sample jitter, same as a real optical
    wander = np.convolve(rng.normal(0, 1.0, n + 40), np.ones(41) / 41, "same")[:n]
    hr = hr + wander * 1.6 + rng.normal(0, 0.9, n)

    # steps per 10 s bin -- integer counts, which is what a pedometer reports
    steps = rng.poisson(np.clip(cad * DT_MIN, 0, None)).astype(int)

    # A derivative detector can only see a heart rate that is CLIMBING. So the
    # answer key distinguishes the two halves of a stress response instead of
    # calling the whole span one thing: the rise is stress_onset and is scored,
    # the elevated-but-flat tail is stress_sustained and is reported separately.
    # The split is taken from the generator's own noiseless derivative, not
    # from anything the detector produced.
    true_slope = np.gradient(clean, GRID_S) * 60.0
    flat = (kind == "stress_onset") & (true_slope < ONSET_SLOPE)
    kind = np.where(flat, "stress_sustained", kind).astype(object)

    for s, d in DROPOUTS:
        a, b = int(s / DT_MIN), int((s + d) / DT_MIN)
        hr[a:min(b, n)] = np.nan

    return cad, steps, hr, kind, label


def main(hr_path="data/real/hr_10s.csv",
         dst="data/real/walk_10s.csv", ev="data/real/walk_events.csv"):
    real = pd.read_csv(hr_path, parse_dates=["timestamp"])
    n = len(real)
    rng = np.random.default_rng(SEED)
    cad, steps, hr, kind, label = build(n, rng)

    # share the real recording's clock, so the two tracks sit on one axis
    out = pd.DataFrame({
        "timestamp": real["timestamp"],
        "steps": steps,
        "hr_bpm": np.round(hr, 1),
        "cadence_true_spm": np.round(cad, 1),
    })
    pathlib.Path(dst).parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(dst, index=False, date_format="%Y-%m-%d %H:%M:%S")

    # ground truth, as spans -- the answer key for the synthetic half only
    rows, i = [], 0
    while i < n:
        j = i
        while j + 1 < n and kind[j + 1] == kind[i] and label[j + 1] == label[i]:
            j += 1
        rows.append({"start": real["timestamp"].iloc[i],
                     "end": real["timestamp"].iloc[min(j + 1, n - 1)],
                     "kind": kind[i], "label": label[i]})
        i = j + 1
    gt = pd.DataFrame(rows)
    gt.to_csv(ev, index=False, date_format="%Y-%m-%d %H:%M:%S")

    print(f"grid          {n:,} bins @ {GRID_S}s  ({n*GRID_S/3600:.2f} h, "
          f"matched to the real recording)")
    print(f"steps         {steps.sum():,} total, peak cadence {cad.max():.0f} spm")
    print(f"HR            {np.nanmin(hr):.0f}-{np.nanmax(hr):.0f} bpm")
    print(f"walking       {(cad>30).sum()*DT_MIN:.0f} min in "
          f"{sum(1 for r in rows if r['kind']=='activity')} bouts")
    print(f"labelled      {len(gt)} spans, "
          f"{(gt.kind=='stress_onset').sum()} onsets / "
          f"{(gt.kind=='stress_sustained').sum()} sustained")
    print(f"-> {dst}\n-> {ev}")


if __name__ == "__main__":
    main()
